"""empty message

Revision ID: 2b6bbee074d6
Revises: a6746c3e6cfa
Create Date: 2025-05-24 21:36:55.449095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6bbee074d6'
down_revision = 'a6746c3e6cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_cache_cs2',
    sa.Column('market_hash_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('market_hash_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_cache_cs2')
    # ### end Alembic commands ###
