"""Add rarity_color and rarity_name to db

Revision ID: 396dfb968082
Revises: beca5d716246
Create Date: 2025-05-25 00:52:42.216025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396dfb968082'
down_revision = 'beca5d716246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cs2_inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rarity_internal_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rarity_color_hex', sa.String(length=7), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_cs2_inventory_items_rarity_internal_name'), ['rarity_internal_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cs2_inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_cs2_inventory_items_rarity_internal_name'))
        batch_op.drop_column('rarity_color_hex')
        batch_op.drop_column('rarity_internal_name')

    # ### end Alembic commands ###
