"""Add UserCS2InventoryItem table

Revision ID: a6746c3e6cfa
Revises: a679bd8545c2
Create Date: 2025-05-24 21:35:54.463295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6746c3e6cfa'
down_revision = 'a679bd8545c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cs2_inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=255), nullable=False),
    sa.Column('class_id', sa.String(length=255), nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market_hash_name', sa.String(length=255), nullable=False),
    sa.Column('item_type_str', sa.String(length=100), nullable=True),
    sa.Column('rarity_str', sa.String(length=100), nullable=True),
    sa.Column('exterior_str', sa.String(length=100), nullable=True),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('current_market_price', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=10), nullable=True),
    sa.Column('last_price_update', sa.DateTime(), nullable=True),
    sa.Column('tradable', sa.Boolean(), nullable=True),
    sa.Column('marketable', sa.Boolean(), nullable=True),
    sa.Column('snapshot_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', 'asset_id', name='uq_user_game_cs2_asset')
    )
    with op.batch_alter_table('user_cs2_inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_cs2_inventory_items_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_cs2_inventory_items_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_cs2_inventory_items_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_cs2_inventory_items_market_hash_name'), ['market_hash_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_cs2_inventory_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cs2_inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_cs2_inventory_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_cs2_inventory_items_market_hash_name'))
        batch_op.drop_index(batch_op.f('ix_user_cs2_inventory_items_instance_id'))
        batch_op.drop_index(batch_op.f('ix_user_cs2_inventory_items_class_id'))
        batch_op.drop_index(batch_op.f('ix_user_cs2_inventory_items_asset_id'))

    op.drop_table('user_cs2_inventory_items')
    # ### end Alembic commands ###
